### 1. Importando a Biblioteca
A convenção universal da comunidade é importar o Pandas com o alias pd

In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\vinic\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vinic\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinic\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\vinic\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\vinic\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np # Frequentemente usamos junto com o Pandas
print(f"Versão do Pandas: {pd.__version__}")

Versão do Pandas: 3.0.1

### 2. Estrutura de Dados: Series e DataFrames
- **Séries:** É uma matriz unidimensional com rótulos (índices). Pode ser vista com o uma única coluna de uma tabela.
- **DataFrame:** É uma estrutura bidimensional (linhas e colunas), como uma planilha completa. É essencialmente um conjunto de Series.

In [ ]:
# Criando uma Series
notas = pd.Series([8.5, 9.0, 7.5, 10.0], index=['Aluno A', 'Aluno B', 'Aluno C', 'Aluno D'])
print("Exemplo de Series:\n", notas, "\n")

Exemplo de Series:
 Aluno A     8.5
Aluno B     9.0
Aluno C     7.5
Aluno D    10.0
dtype: float64

In [ ]:
# Criando um DataFrame a partir de um dicionário (útil para testes locais)
dados_turma = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'Idade': [20, 22, 21, 23],
    'Nota_Final': [8.5, 7.0, 9.5, 6.5],
    'Aprovado': [True, True, True, False]
}
df = pd.DataFrame(dados_turma)
print("Exemplo de DataFrame:")
display(df) # O 'display' renderiza uma tabela mais bonita no Jupyter do que o print1

Exemplo de DataFrame:

     Nome  Idade  Nota_Final  Aprovado
0     Ana     20         8.5      True
1   Bruno     22         7.0      True
2  Carlos     21         9.5      True
3   Diana     23         6.5     False

0       Ana
1     Bruno
2    Carlos
3     Diana
Name: Nome, dtype: str

0     True
1     True
2     True
3    False
Name: Aprovado, dtype: bool

### 3. Lendo Dados de Arquivos Externos (CSV)

Na prática real de análise, nós raramente geramos os dados manualmente no código. O fluxo normal é ler os dados diretamente de arquivos, sendo o formato CSV o mais comum.

In [5]:
# O comando abaixo é o padrão para ler arquivos CSV.
# df_csv = pd.read_csv('caminho/para/seu_arquivo.csv')

# Exemplo prático carregando um dataset público diretamente de uma URL para demonstração:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df_titanic = pd.read_csv(url)
print("Dados carregados com sucesso!")
display(df_titanic)

Dados carregados com sucesso!

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
# .head() mostra as 5 primeiras linhas do DataFrame
display(df_titanic.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
print("\n--- Formato do Dataset (linhas, colunas) ---")
print(df_titanic.shape)

--- Formato do Dataset (linhas, colunas) ---
(891, 12)

In [8]:

print("\n--- Informações Gerais e Tipos de Dados ---")
df_titanic.info()

--- Informações Gerais e Tipos de Dados ---
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [9]:
print("\n--- Resumo Estatístico das Colunas Numéricas ---")
display(df_titanic.describe())

--- Resumo Estatístico das Colunas Numéricas ---

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### 5. Seleção e Filtragem de Dados

Como selecionar colunas específicas e filtrar linhas baseadas em condições

In [22]:
# Selecionando apenas uma colunas (retorna uma Series)
idades = df_titanic['Age']
print(idades)

# Selecionando múltiplas colunas (retorna um novo DataFrame)
df_reduzido = df_titanic[['Name', 'Age', 'Survived']]
print(df_reduzido)

# Filtragem (Querying): Selecionando apenas passageiros com mais de 60 anos
passageiros_idosos = df_titanic[df_titanic['Age'] > 60]
print(f"Total de passageiros com mais de 60 anos: {len(passageiros_idosos)}")

# FIltragem com múltiplas condições (Use & para E, | para OU)
# Ex: Mulheres que sobrevivem na 1º classe
filtro = (df_titanic['Sex'] == 'female') & (df_titanic['Survived'] == 1) & (df_titanic['Pclass'] == 1)
mulheres_1a_classe = df_titanic[filtro]

print('Mulheres da 1º classe que sobreviveram:', len(mulheres_1a_classe))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
                                                  Name   Age  Survived
0                              Braund, Mr. Owen Harris  22.0         0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                               Heikkinen, Miss. Laina  26.0         1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                             Allen, Mr. William Henry  35.0         0
..                                                 ...   ...       ...
886                              Montvila, Rev. Juozas  27.0         0
887                       Graham, Miss. Margaret Edith  19.0         1
888           Johnston, Miss. Catherine Helen "Carrie"   NaN         0
889                              Behr, Mr. Karl Howell  26.0         1
890                                Dooley, Mr. Patrick  32.0         0

[891 rows x 3 columns]
Total de passageiros com mais de 60 anos: 22
Mulheres da 1º classe que sobreviveram: 91

In [23]:
exemplo_1 = np.array([201, 804, 98, 0, 2, 1000, 300])
exemplo_2 = np.array(['Marta', 'Paulo', 'Tiago', 'Vinicius', 'Marcelo', 'Renan', 'Brenda'])
dicionario = {
    "valores": exemplo_1,
    "nomes": exemplo_2
}

tabela_exemplo = pd.DataFrame(dicionario)
display(tabela_exemplo)

   valores     nomes
0      201     Marta
1      804     Paulo
2       98     Tiago
3        0  Vinicius
4        2   Marcelo
5     1000     Renan
6      300    Brenda